spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: spring-boot-demo-config-server-dev
---
spring:
  profiles: test
  application:
    name: spring-boot-demo-config-server-test